fix(examples): fix third option of fourth part of Groupon's exercise
fforres/preguntas-y-respuestas-entrevistas-frontend pull request #53
Opened 2018-01-12 23:53 UTC by LuisUrrutia

La parte 3 del ejercicio de Groupon nos dice que las funciones tick() y tock() son manejadas por otro equipo, por lo tanto no tendríamos acceso a modificar dichas funciones.

Mi propuesta es aprovechar la coerción de tipos booleanos a enteros (true -> 1, false -> 0), en conjunto a la conversión de valores "Decimales" a caracteres, donde el valor 105 corresponde al carácter "i", mientras que el valor 111 corresponde al carácter "o".

Con esas cosas en cuenta, el código habla por si mismo.

2018-01-16 18:55 UTC, fforres commented
Hey @LuisUrrutia, muchas gracias por tu PR, esta cool el approach de usar `new Function`.
Podrias agregarlo si como una nueva opcion 4?

2018-01-16 18:56 UTC, fforres requested changes
Hey @LuisUrrutia, muchas gracias por tu PR, esta cool el approach de usar `new Function`. 🤘 
Podrias agregarlo si como una nueva opcion 4?

2018-01-18 11:19 UTC, LuisUrrutia commented
@fforres si, podría, pero el problema es que la opción 3 no cumple con los requisitos planteados en la parte 3, ya que se modifican las funciones "tick" y "tock".

> ahora "tick" y "tock", son 2 funciones que manejan otros 2 equipos

Si son funciones que manejan otros 2 equipos, en teoría, no deberíamos poder modificarlas para que cambien el valor de una variable "global".

Quizás sea necesario aclarar que las restricciones propuestas en la parte 3 no aplican para la parte 4.

2019-01-22 17:59 UTC, fforres commented
1 año de demora en mi followup 😅
Toda la razón con lo que las funciones no deberiamos modificarlas.

El uso de `String.fromCharCode` esta bién cool, quizas un poco high level? me gustaría dejar el repo con opciones para todo nivel.

Te parece si agregamos tu opción como 4 y cambiamos la 3 a:

`Guardar una referencia a tick y tock en nuestras propias variables`
```
const nuestroPropioTick = () => {
	tick();
	funct = nuestroPropioTock
}
const nuestroPropioTock = () => {
	tock();
	funct = nuestroPropioTick
}
const funct = nuestroPropioTick;
const tickTock = () => {
  funct();
}
```

???

2023-06-13 00:37 UTC, closed without merging